// filter actions
const ADD_FILTER = "ADD_FILTER";
const REMOVE_FILTER = "REMOVE_FILTER";
const EDIT_FILTER = "EDIT_FILTER";
const CLEAR_FILTER = "CLEAR_FILTER";

// trip actions
const FETCH_TRIPS_REQUEST = "FETCH_TRIPS_REQUEST";
const FETCH_TRIPS_SUCCESS = "FETCH_TRIPS_SUCCESS";
const FETCH_TRIPS_FAILURE = "FETCH_TRIPS_FAILURE";

// ticket actions
const ADD_TICKET = "ADD_TICKET";
const REMOVE_TICKET = "REMOVE_TICKET";

export {
  ADD_FILTER,
  REMOVE_FILTER,
  EDIT_FILTER,
  CLEAR_FILTER,
  ADD_TICKET,
  REMOVE_TICKET,
  FETCH_TRIPS_REQUEST,
  FETCH_TRIPS_SUCCESS,
  FETCH_TRIPS_FAILURE,
};
