// filter actions
const ADD_FILTER = "ADD_FILTER";
const REMOVE_FILTER = "REMOVE_FILTER";
const EDIT_FILTER = "EDIT_FILTER";
const CLEAR_FILTER = "CLEAR_FILTER";

// trip actions
const ADD_TRIPS = "ADD_TRIPS";
const CLEAR_TRIPS = "CLEAR_TRIPS";

// ticket actions
const ADD_TICKET = "ADD_TICKET";
const REMOVE_TICKET = "REMOVE_TICKET";


export {ADD_FILTER, REMOVE_FILTER, EDIT_FILTER, CLEAR_FILTER, ADD_TICKET, REMOVE_TICKET, ADD_TRIPS, CLEAR_TRIPS}